site_name: xTLDR
site_url: https://xtldr.com/
theme:
  name: material
  icon:
    logo: simple/lightning
  favicon: assets/favicon.png
  features:
    - navigation.top
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

plugins:
  - search
  - glightbox
  - social:
      cards_layout_options:
        background_color: black

extra_css:
  - assets/toc_custom.css
  - assets/github-permalink-style.css
  - assets/theme.css
  - assets/search.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: ""
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
