site_name: xTLDR
site_url: https://xtldr.com/
site_description: The absolute fastest way to get started with X.
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: simple/lightning
  favicon: assets/favicon.png
  features:
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

plugins:
  - search
  - awesome-pages
  - glightbox
  - social:
      cards_layout_options:
        background_color: black
  - git-committers:
      repository: KarthikAbiram/xtldr
      branch: main
      exclude:
        - index.md
        - books/index.md
  - git-revision-date-localized:
      enable_creation_date: true
      exclude:
        - index.md
        - books/index.md

extra_css:
  - assets/toc_custom.css
  - assets/github-permalink-style.css
  - assets/theme.css
  - assets/search.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: ""
      # toc_depth: 2
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

extra:
  generator: true # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  analytics:
    provider: google
    property: G-EF6S4TB0C5
    # feedback:
    #   title: Was this page helpful?
    #   ratings:
    #     - icon: material/emoticon-happy-outline
    #       name: This page was helpful
    #       data: 1
    #       note: >-
    #         Thanks for your feedback!
    #     - icon: material/emoticon-sad-outline
    #       name: This page could be improved
    #       data: 0
    #       note: >-
    #         Thanks for your feedback! Help us improve this page by
    #         using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSfnFR62swIf4p_vJ9y8vGQgTKho5QGHmpr9zAvr3JzlSniRnw/viewform?usp=pp_url&entry.31431447={url}" target="_blank" rel="noopener">feedback form</a>.
